---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/traefik.yaml
  - middlewares/add-secure-headers.yaml
  - middlewares/avg-100-burst-50-limit.yaml
  - middlewares/chains/authentik-auth.yaml
  - middlewares/chains/no-auth.yaml
  - middlewares/forward-auth-authentik.yaml
  - middlewares/https-redirect.yaml
  - middlewares/strip-host-prefix.yaml
  - ingress/dashboard-access.yaml
