---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints-cm
data:
  reconfigure-admin-user.yaml: |-
    version: 1
    metadata::
      labels:
        blueprints.goauthentik.io/description: Update admin user's user info
      name: Users - Modify superuser user data
    entries:
      - model: authentik_blueprints.metaapplyblueprint
        attrs:
          identifiers:
            name: Default - Out-of-box-experience flow
          required: true
      - model: authentik_core.user
        identifiers:
          pk: 1
        attrs:
          username: gord
          name: "God™"
        state: present
      # need to modify the policy that checks whether the admin user password needs updating
      # the check relies on the username which is changed above
      - model: authentik_policies_expression.expressionpolicy
        identifiers:
          name: default-oobe-prefill-user
        attrs:
          expression: |
            # This policy sets the user for the currently running flow
            # by injecting "pending_user"
            akadmin = ak_user_by(pk=1)
            context["flow_plan"].context["pending_user"] = akadmin
            return True
        state: present
      # need to modify the policy that checks whether the admin user password needs updating
      # the check relies on the username which is changed above
      - model: authentik_policies_expression.expressionpolicy
        identifiers:
          name: default-oobe-password-usable
        attrs:
          expression: |
            # This policy ensures that the setup flow can only be
            # executed when the admin user doesn't have a password set
            akadmin = ak_user_by(pk=1)
            return not akadmin.has_usable_password()
        state: present
