---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# custom index.html page
configMapGenerator:
- name: authentik-blueprints-cm
  namespace: silphco-infrastructure
  files:
    - bp.yaml

helmChartInflationGenerator:
- chartName: authentik
  chartRepoUrl: https://charts.goauthentik.io/
  chartVersion: 2023.3.1
  # override with these custom values
  values: values.yaml