---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: silphco-infrastructure

# custom index.html page
configMapGenerator:
- name: authentik-blueprints-cm
  namespace: silphco-infrastructure
  files:
    - bp.yaml
generatorOptions:
  disableNameSuffixHash: true # use a static name

helmChartInflationGenerator:
- chartName: authentik
  chartRepoUrl: https://charts.goauthentik.io/
  chartVersion: 2023.3.1
  releaseName: authentik
  # override with these custom values
  values: values.yaml