---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql-secrets
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
    password: AgDO8ZIXPNgM1v9wRVwWv0o29renhVSiHlOtGW+30umbqitplR4diHCGTfRkO/zvRedUkrFPndOuNon1ywYCsisYlTi+Moh7oLAH/026k24zWGT9AZlHLII2QDfPEJv2AvxdYM4UiiQBKCdFGFFpSenqhD82fBwOYPq4T4ecXnVbF9ifBTy9XtxfeBvApkV93msYLBIpzmfIsdXLkbW1gOjbSpX5L6M6HSDV+aU3UvyIKKaGEBmsliscFNqEDVKnsTq98EMeWK59xkfBzjNBFr3QIglhjU7L2qDP+E8qPTMwhEaVuGo/T9E5w5dHEhdK9CkEdPVGNk8sG/pt8PCUZ/lTC4GHWE90hYIlmpo2N3MowRzaxCCbln0xPW/5YbiVmnQ/FeSUcLOi1Cw5+V/vIUXH3607dJcSjw3Ua+A1OwZ8D/JiLqlAznl/eKe+BmgAtFx+mQvqh764oA/X7/DYfZuBktN4D4NmVg9mHfNDSQtvkocUwrCCqq4o/kAgEVfTlfDu0aPl32jyYrGD4vLyAdXIav48yhdp/rYTdOADlipurB8Tg4L8HbexoCeKY+cikle9IP9/VI5MRaFz5+1aIm+OH+k7xBhE5g/5JH0NMLUiWBgZHG/miYU+LhyjqS29Z1dkFAKcIicoMowYZgjkJzZR1niPewaBbCwsrhe6BHamxha8fND+aAddTdoeAjtQuQwgBS1casQh77KSjGYrCdr6NrqPWD9OjuunKNt3xbTwSNWGI0TVfK8OGGi1gtn80C0=
