---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql-secrets
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
    password: AgAJhehm2U84di/HGOPXPkbMtFU23+okT+yGUJsDwu5E23V50+ChjtF72fyj0anm16HKfOCjRwQUPQFMIP0bTWPaZaejmnUaqhKB2+aOMM8s9ZyZpQ/8PHvnFKXnJMLruiS21YWJhlMV2RhCz1FfKXA9XJvFuDEFlh1B6hzBncvYZ60bvxnvioxAkhGY1sua8rAQxQrXiyGqfJ1ASxZ2YGVKC0UjQ0WezdW0jNs6W5hqLxpFicWtolGJjLe70+AIo7lINi3HRWH296+4n/VGI3ieEPOg716H/8oezSJkKjwkSN1XyPgS4dptLt9Mbiu3boJc9wxcuKPcVIeoQlJLZ8xU/MsDRAEo0j6x/Gfveq7vQbDIzc5PxBAFayF+I/lOuCXIL2N5c6A0DpPdPiauz98Sg78JLLm43Sff5kbBsjza8ZG8Xc8ZL78pODo8gSqSZrxgy/IOkyxVG14arkzgPklR8zmSq0lckS87UwLvKQ63G73t2HZb8xmDlIRjXNEFVIvLi5yqvIzI6ma/bbrNtI2ik6Qw+ORY89CbZuFnqtMPM8UGU6SpMz6PiWLHGATtSJSNyVugpzpnKjuIwgDWFjM729lJoO346aJ7UNfIJ062De7pkc+R1qYK85La7JQ/PL6Vk64vjzarLvd4aTdQV3pYazRc0+OVuBt2dI2DXieoVLlZZc3ZiLNoC+sblLyoX3i2f7oVQQej5SQcNMWr1xwweD23PlddGPZNECyOrVOxWpOoExjr4vRAgfCZ4FeKNf8=
