---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-app-secrets
  namespace: silphco-infrastructure
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    secretKey: AgCnroFDCCyf+soKJN+kJHnBj9W2qaAl2GlGtWxjsTeKeidUktMDlAVQ774JrGi3WJQAFbH0+3zh2kVrVKb5OBDf/fW/ysEwEsHl2nGkeLtezjveUHG7MNP2k46J7wiIiovXuBmT+GkGLA0+MDsaMSTKO/9gNVMqgT2gPLGk8jYgnylPOVTiBbXjqEPzX5y1zaFpFh+Om0qSLN7Bk4o7Pu/U7wfXRUASErLLjtn1rCOyvwrgBbnQSYJaENSNsa9Z+dS8gBXvxjx3tlrsz/qGefVNWwEQIjtXw2yGpW1fEMxjh+I+4M1jqgIJ4VeCWB17ZxAmgPzUYOQxqfMSjd90CajB4Id9n4IlXhfp0OH+bG4lASz8ZBpL+CPAXzNiUTD/Jb8KGrUXKUK1DB1OQnIEByNvLbeayQSRikjM0y1QvUes7mp+AvlK7+2gmS85piwRYHrFqyyk5SyWNQHcO+Ep+goe68Q6+kmUvwo4mGv8NqaS3xe9+F3X29wwGN0HE6KSK78oSF21rXL5+VveIP9YVWl8Fwskkrx2+nBU0S0ZZgYG5cevmRpyH1U/e93BNsiyFIc09yJiN1l+OOwUBaxRKgUdT/yNh6G3C2GKQ3v1uxmS4p6061DJRH2Zv9aX2Mv15qjYITLK2n3d0SccIAicXawYX+0J+QPHY2nbSw3+Aamr65hcc3SchYc1VCSH54iBT9o7cB6PAQebS6uffWtASf71kFqox9sUoE26VBrEbWiYs1Y69Z9Le1KFv+OpFgEWQ9A=
  template:
    type: Opaque
