---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-app-secrets
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
    secretKey: AgCKn+nFmA5tTKlUApmNr0f4tXvteF7949OV+bO2bAOVIfpoHsb0HV20VVdWObTBTs20rMzTKreSjmkkhFGUFK0R6kbnT8PZWURJmV1juVK1Vws/YkgureeAe6p/IagZxwqt6GGXjUD6+6EfLTGMLA29LXTRUB2Fwm2HR2THMjyv1wq5KARxglg/BrTbBrSrODG6//RPhFIcE2IVOE3+Mu+qMntuAtAYi4+XHbgk4hB3n8G8exkV13K8wO4YwShTUQA2QlXMUKE6W/1eUhUIZ/0HSLSMb10CZAloP4ywKMhdfmOLk00oKNKIYAeNG8KhRM9q5ktgRLimqGYYxwcFXniSC7fVltaXX93EXfRmkw0HCCMRbOS+U8uihhKRcGnxG0Wmei3Z+4OQ6YbUvoLOKMUffmKu8O7JZRzEQSnrL+IRRvpfSDQat0mkFMoYbKtzL1ies0Ia7egPom11z4Wdxn2yj6SSPv1yiSEUuCEGyJ5+VNmooWHDxJv/zB+Wb6FFAUIOlJNYHAYn3hzOXGfYfevTu/l3c9Ou6zHyGrInMRDkvfriFVuCRxGdscJ0qskKyce9jNzXW81LTI6EK5urAGFVuU/9GgrPcHdwctQdfbHidluBZ2HCD/lfnJ5hrVFUSQnr61qqO7KRaDUZjJuY80CJbkDc0bdyhsDnC1EVqtzbVHvSRvq8ufpdMtALIxgFulUgHylfH8Kse52RPbqIFgfG5lL+MRvXDlBJtalaC4e3q3vVysvKn1H1IzJDviOUjP4=
