---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.6.7

# additional resources like ingress rules, cluster and repository secrets.
resources:
- namespaces/argocd.yaml
- ingress/argocd-web-ui.yaml
- projects/silphco-infrastructure.yaml
- apps/argocd.yaml

# changes to config maps
patchesStrategicMerge:
- overlays/weaken-argocd-api-server.yaml
- overlays/constrain-argocd-server-resources.yaml
- overlays/enable-helm-chart-kustomization.yaml
- overlays/configure-argo-cd-repo.yaml
