---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.6.7

# additional resources like ingress rules, cluster and repository secrets.
resources:
- ns-argocd.yaml
- ingress-argocd-web-ui.yaml
- app-argocd.yaml

# changes to config maps
patchesStrategicMerge:
- path: overlays/weaken-argocd-api-server.yaml
- path: overlays/constrain-argocd-server-resources.yaml
- path: overlays/enable-helm-chart-kustomization.yaml
- path: overlays/configure-argo-cd-repo.yaml
