---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: silphco-infrastructure
  sources:
    - chart: authentik
      repoURL: https://charts.goauthentik.io/
      targetRevision: 2023.3.1
      helm:
        valueFiles:
        - $values/authentik/values.yaml
    - repoURL: https://github.com/cskwrd/trash-infra.git
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: silphco-infrastucture
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
