---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: silphco-infrastructure
  source:
    path: sealed-secrets
    repoURL: https://github.com/cskwrd/trash-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
